//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalBlog.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int TaskNo { get; set; }
        public string Task { get; set; }
        public string Priority { get; set; }
    }
}
